### ISSUE TITLE
Addon failed to import in godot 3.1

### ISSUE THREAD

**Issue by DenpaBorisu** [godot-addons/godot-behavior-tree-plugin#17]
Getting this error when loading the addon on godot 3.1, leading to it being unable to be activated as a plugin.
`SCRIPT ERROR: GDScript::reload: Parse Error: Expected ')' in expression
          At: res://addons/godot-behavior-tree-plugin/failer.gd:14
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:580
SCRIPT ERROR: GDScript::reload: Parse Error: Could not fully preload the script, possible cyclic reference or compilation error. Use 'load()' instead if a cyclic reference is intended.
          At: res://addons/godot-behavior-tree-plugin/plugin_script.gd:37
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:580`

**Comment by DenpaBorisu** [comment]
so changing all preload() to load() in plugin_script.gd, seem to fix the problem

**Comment by brandonlamb** [comment]
coming back to godot after a 6 month hiatus or so from game dev, will check out these addons in the latest version and make updates soon

**Comment by lmerriam** [comment]
After fixing the preload issue on that file I get another error: `res://addons/godot-behavior-tree-plugin/failer.gd:14 - Parse Error: Expected ')' in expression
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR`

Would love to see 3.1 compatibility!
