### ISSUE TITLE
Composite types do not resume at ERR_BUSY nodes

### ISSUE THREAD

**Issue by aclave1** [godot-addons/godot-behavior-tree-plugin#28]
The documentation specifies:
> Will resume at the ERR_BUSY-returning child

But when I test/look at the code, I don't see any logic to detect an ERR_BUSY response, or resume from it. 

I've modified the library to add this functionality, let me know if you'd like me to PR. It's only a couple of lines in each file.

**Comment by brandonlamb** [comment]
sure!

**Comment by DagobertDev** [comment]
That would be great, thanks

**Comment by aclave1** [comment]
Working on a game jam which ends tomorrow, I will submit a PR after that.

**Comment by brandonlamb** [comment]
Sweet! I have always been philosophically interested in doing a game jam, but too lazy lulz

**Comment by aclave1** [comment]
@brandonlamb [Here's the game](https://itch.io/jam/godot-wild-jam-21/rate/644961)! And it's using this behavior tree plugin(with the modifications mentioned in the bug). This was my first jam. It was more fun than I thought it'd be. I was able to do it at my own pace over the course of 10 days. I will work on this PR soon

**Comment by brandonlamb** [comment]
Wow that was only ~1 week? and 3d! i way too dumb for that

**Comment by aclave1** [comment]
@brandonlamb looks like this is actually implemented by the mem_sequence and the mem_selector nodes. I was only using the normal sequence and selector nodes, I never even really noticed the mem variants! I will close this issue 😅
