### ISSUE TITLE
issue with BehaviorInverter

### ISSUE THREAD

**Issue by torohaifisch** [godot-addons/godot-behavior-tree-plugin#5]
hello i've been messing around with your plugin doing some basic stuff to learn how it works but the inverter is throwing an error in the code and i dont know how to fix it, i hope u can help with this because its a really cool plugin

![image](https://user-images.githubusercontent.com/5290254/38653135-9799f496-3ddf-11e8-9722-84c1c274b7fb.png)

**Comment by brandonlamb** [comment]
I haven't touched any gdscript/godot programming for a few months, but my first guess is it looks like a syntax issue on your line 14. I would try with and without the typeof or extends check and see if one of those is the issue

**Comment by torohaifisch** [comment]
seems like it's extends, should be changed to `result is BehvError`
considering this was reported to godotengine https://github.com/godotengine/godot/issues/11596
