### ISSUE TITLE
memory usage 

### ISSUE THREAD

**Issue by torohaifisch** [godot-addons/godot-behavior-tree-plugin#6]
hello
i dont know if this is expected but i was checking the resource monitor and i noticed a really high memory usage of my game, considering the game without the behavior tree stays at 50mb of ram and an object count of 845, with the behavior tree the ram usage and object count goes up and up.

i had a more complex tree but for testing purposes i put a tree with just 1 child to check the usage

![image](https://user-images.githubusercontent.com/5290254/39071574-f64d9e2c-44bd-11e8-810d-1b62277852ab.png)

**Comment by brandonlamb** [comment]
Are you saying you think that it looks like there is a memory leak? I've not dived that deep into Godot yet myself to debug something like that.

An additional 50m *sounds* like a lot at first glance, but then again a small REST API in node/java could run in 75 megs so it's hard for me to compare "what is 50m".

If the memory just continues to increase, that does seem like a memory leak (based on really only the screenshot)

**Comment by torohaifisch** [comment]
yes it seems like a memory leak, what i think the problem could be when you instance a tick, what happens with it when it reaches the end and its not needed, does it get freed from memory or it stays there forever? considering the code of the behavior tree gets executed on process it instances new ticks every time, that could be why the object count keeps going up, but i am not sure, i will leave it alone for an hour or something to check if it stops

**Comment by torohaifisch** [comment]
link related https://github.com/godotengine/godot/issues/8985
seems like objects not being deleted (tick instances i think)

this is after an hour 254k objects:
![image](https://user-images.githubusercontent.com/5290254/39088625-df1ecbc6-458b-11e8-87f7-584f8f2189d2.png)
